name: DelicateGuild
version: '${project.version}'
main: github.serliunx.delicateguild.DelicateGuild
authors: [ SerLiunx ]
softdepend: [PlaceholderAPI]
description: a guild plugin.
api-version: 1.17
commands:
  delicateguild:
    aliases: ["dguild", dg]
    description: main command for DelicateGuild.
